rawData = out.signalOut(1,1,:); % set to raw recieved bits
rawData = reshape(rawData(1, 1, :), 1, length(rawData(1, 1, :)));
binary = true;
dim = 8;
recievedBits = parse(rawData, dim, binary);

image2 = decode(recievedBits, dim, binary); %dim generated by fullSend.m
colormap(gray)